import pytest
import datetime
from fastapi.testclient import TestClient
from app.database import models

def test_assessment_review_workflow(client: TestClient, auth_headers_user1: dict, auth_headers_user2: dict, db_session):
    # Setup User 1 (borrower, role='user')
    user1 = db_session.query(models.User).filter(models.User.uid == "user_alpha_1").first()
    if not user1:
        user1 = models.User(uid="user_alpha_1", email="borrower@test.com", role="user")
        db_session.add(user1)
    else:
        user1.role = "user"
    db_session.commit()

    # Create business and assessment for User 1
    bus = models.Business(
        user_id="user_alpha_1",
        name="Review Test Business",
        industry="Retail",
        age=5,
        employees=10
    )
    db_session.add(bus)
    db_session.commit()
    db_session.refresh(bus)

    ass = models.Assessment(
        business_id=bus.id,
        annual_revenue=500000.0,
        monthly_cash_flow=40000.0,
        monthly_expenses=30000.0,
        existing_debt=100000.0,
        digital_transactions=200,
        utility_payment_score=80.0,
        invoice_payment_score=85.0,
        previous_defaults=0,
        review_status="pending"
    )
    db_session.add(ass)
    db_session.commit()
    db_session.refresh(ass)

    pred = models.Prediction(
        assessment_id=ass.id,
        default_probability=25.0,
        risk_level="LOW",
        confidence=88.0,
        top_factors=["Good Cash Flow"],
        model_version="1.0"
    )
    db_session.add(pred)
    db_session.commit()

    # 1. Normal user (borrower) attempts to review assessment -> Expected 403 Forbidden
    resp = client.put(
        f"/api/assessments/{ass.id}/review",
        json={"review_status": "approved", "review_notes": "Self approval attempt"},
        headers=auth_headers_user1
    )
    assert resp.status_code == 403
    assert "Access denied" in resp.json()["detail"]

    # Setup User 2 (analyst, role='analyst')
    user2 = db_session.query(models.User).filter(models.User.uid == "user_beta_2").first()
    if not user2:
        user2 = models.User(uid="user_beta_2", email="analyst@test.com", role="analyst")
        db_session.add(user2)
    else:
        user2.role = "analyst"
    db_session.commit()

    # 4. Invalid review status rejected -> Expected 422
    resp_inv = client.put(
        f"/api/assessments/{ass.id}/review",
        json={"review_status": "invalid_status"},
        headers=auth_headers_user2
    )
    assert resp_inv.status_code == 422

    # 2. Analyst can review assessment -> Expected 200
    # 5. Review notes saved correctly
    # 6. reviewed_by is taken from authenticated user
    # 7. reviewed_at is generated by backend
    resp = client.put(
        f"/api/assessments/{ass.id}/review",
        json={"review_status": "approved", "review_notes": "Financials verified, clean utility score."},
        headers=auth_headers_user2
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["review_status"] == "approved"
    assert data["review_notes"] == "Financials verified, clean utility score."
    assert data["reviewed_by"] == "user_beta_2"
    assert data["reviewed_at"] is not None

    # 8. Review creates notification for borrower (User 1)
    notif = db_session.query(models.Notification).filter(models.Notification.user_id == "user_alpha_1").first()
    assert notif is not None
    assert "APPROVED" in notif.message

    # 9. Review creates AuditLog entry
    audit = db_session.query(models.AuditLog).filter(
        models.AuditLog.action == "REVIEW_ASSESSMENT",
        models.AuditLog.resource_id == str(ass.id)
    ).first()
    assert audit is not None
    assert audit.user_id == "user_beta_2"
    assert audit.details["review_status"] == "approved"

    # 3. Admin can review assessment -> Expected 200
    user3 = models.User(uid="user_admin_3", email="admin@test.com", role="admin")
    db_session.add(user3)
    db_session.commit()
    auth_headers_admin = {"Authorization": "Bearer test_token:user_admin_3:admin@test.com:Super Admin"}

    resp_admin = client.put(
        f"/api/assessments/{ass.id}/review",
        json={"review_status": "needs_info", "review_notes": "Additional audited balance sheet requested."},
        headers=auth_headers_admin
    )
    assert resp_admin.status_code == 200
    data_admin = resp_admin.json()
    assert data_admin["review_status"] == "needs_info"
    assert data_admin["reviewed_by"] == "user_admin_3"
