import datetime

class ReportService:
    def generate_report_data(self, business_data: dict, assessment_data: dict, prediction_data: dict, model_version: str = "1.0.0") -> dict:
        """
        Compiles business information, assessment parameters, and ML predictions
        into a comprehensive report structure.
        """
        # Calculate financial ratios
        debt = assessment_data.get("existing_debt", 0)
        rev = assessment_data.get("annual_revenue", 1)
        debt_to_rev = debt / max(rev, 1)
        
        cf = assessment_data.get("monthly_cash_flow", 0)
        exp = assessment_data.get("monthly_expenses", 1)
        cash_flow_coverage = cf / max(exp, 1)
        
        report = {
            "metadata": {
                "report_id": f"REP-{datetime.datetime.utcnow().strftime('%y%m%d%H%M%S')}",
                "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
                "model_version": model_version,
                "disclaimer": "This report is generated by an ML decision-support system to predict default probabilities. It is intended to assist in lending assessments but does not constitute a guaranteed lending decision or financial advice."
            },
            "business": {
                "name": business_data.get("name"),
                "industry": business_data.get("industry"),
                "age_years": business_data.get("age"),
                "employees": business_data.get("employees")
            },
            "financial_summary": {
                "annual_revenue": assessment_data.get("annual_revenue"),
                "monthly_cash_flow": assessment_data.get("monthly_cash_flow"),
                "monthly_expenses": assessment_data.get("monthly_expenses"),
                "existing_debt": assessment_data.get("existing_debt"),
                "debt_to_revenue_ratio": round(debt_to_rev, 4),
                "cash_flow_coverage_ratio": round(cash_flow_coverage, 4)
            },
            "alternative_indicators": {
                "digital_transactions_monthly": assessment_data.get("digital_transactions"),
                "utility_payment_score": assessment_data.get("utility_payment_score"),
                "invoice_payment_score": assessment_data.get("invoice_payment_score"),
                "previous_defaults": assessment_data.get("previous_defaults")
            },
            "risk_assessment": {
                "default_probability": prediction_data.get("default_probability"),
                "risk_level": prediction_data.get("risk_level"),
                "confidence_score": prediction_data.get("confidence"),
                "top_factors": prediction_data.get("top_factors", []),
                "positive_factors": prediction_data.get("positive_factors", []),
                "risk_factors": prediction_data.get("risk_factors", [])
            }
        }
        
        return report

report_service = ReportService()
